gha: add cache static file layer.

diff --git a/.github/workflows/build-img4-engage-files.yml b/.github/workflows/build-img4-engage-files.yml
--- a/.github/workflows/build-img4-engage-files.yml
+++ b/.github/workflows/build-img4-engage-files.yml
@@ -1,51 +1,61 @@
-name: "Build Base OS Layer (1 of 4)"
+name: "Build Engage Files Layer (4 of 6)"
 
 on:
-  push:
-    branches-ignore:
-      - main
-      - master
-    tags:
-      - 'v*'
+  repository_dispatch:
+    types: [build_layer_files, build_layer_app_error]
 
 env:
-  IMAGE_STAGE: base
-  DOCKERFILE2USE: docker/dfstage-base.dockerfile
+  IMAGE_STAGE: pyfiles
+  DOCKERFILE2USE: docker/dfstage-pyfiles.dockerfile
+  FROM_LAYER: ${{ github.event.client_payload.layer }}
+  FROM_LAYER_TAG: ${{ github.event.client_payload.layer_tag }}
 
 jobs:
+  build_result:
+    name: "Build App Layer Result [#${{ github.event.client_payload.run_number }}]"
+    runs-on: ubuntu-latest
+    env:
+      RUN_URL: "[Run #${{ github.event.client_payload.run_number }}](${{ github.event.client_payload.run_url }})"
+    steps:
+      - name: "Display Error Msg"
+        if: github.event.client_payload.error_msg != ''
+        run: |-
+          echo -e "::error::${RUN_URL}%0A${{ github.event.client_payload.error_msg }}"
+          exit 1
+      - name: "Display Success Msg"
+        if: github.event.client_payload.build_msg != ''
+        run: |-
+          echo -e "::notice::${RUN_URL}%0A${{ github.event.client_payload.build_msg }}"
+  #endjob build_result
+
   build_cfg:
+    needs: [build_result]
     runs-on: ubuntu-latest
     environment: default
     outputs:
-      REPO_BRANCH: ${{ steps.config_step.outputs.REPO_BRANCH }}
-      REPO_TAG: ${{ steps.config_step.outputs.REPO_TAG }}
       IMAGE_NAME: ${{ steps.config_step.outputs.IMAGE_NAME }}
       IMAGE_TAG: ${{ steps.config_step.outputs.IMAGE_TAG }}
     steps:
       - uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.client_payload.repo.ref_name }}
 
-      - name: "Determine Tag To Use"
+      - name: "Determine Hash Tag To Use"
         id: config_step
+        shell: bash
+        env:
+          REF_NAME: "${{ github.event.client_payload.repo.ref_name }}"
         run: |-
           IMAGE_NAME=${{ github.repository_owner }}/p4-engage
+          echo "${FROM_LAYER#**:}" > base_tag.txt
           source scm/utils.sh
-          IMAGE_TAG_HASH=$(CalcFileArgsMD5 "${DOCKERFILE2USE}")
+          CalcDirArgsHash static media node_modules "engage/static/fonts" "engage/static/bower-engage" > dir_hash.txt
+          IMAGE_TAG_HASH=$(CalcFileArgsHash "${DOCKERFILE2USE}" "base_tag.txt" "package-lock.json" "package.json" "dir_hash.txt")
           IMAGE_TAG="${IMAGE_STAGE}-${IMAGE_TAG_HASH}"
-          echo "::notice::Layer1: ${IMAGE_NAME}:${IMAGE_TAG}"
+          
+          echo "::notice::Engage Static Files Layer: ${IMAGE_NAME}:${IMAGE_TAG}"
           echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
           echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
-          
-          if [[ ${{ github.ref_type }} == 'tag' ]]; then
-            REPO_BRANCH=
-            REPO_TAG=${{ github.ref_name }}
-          else
-            REPO_BRANCH=${{ github.ref_name }}
-            REPO_TAG=
-          fi
-          echo "::notice::Repo Branch=${REPO_BRANCH}"
-          echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_OUTPUT
-          echo "::notice::Repo Tag=${REPO_TAG}"
-          echo "REPO_TAG=${REPO_TAG}" >> $GITHUB_OUTPUT
   #endjob build_cfg
 
   check_image_exist:
@@ -66,7 +76,7 @@ jobs:
     outputs:
       BUILD_STAGE: ${{ steps.is_building.outputs.BUILD_STAGE }}
     steps:
-      - name: Set BUILD_STAGE output
+      - name: "Set BUILD_STAGE output"
         id: is_building
         run: |-
           if [[ -n "${BUILD_ERR_MSG}" ]]; then
@@ -88,7 +98,7 @@ jobs:
     needs: [build_cfg, check_build_image]
     environment: default
     steps:
-      - name: Trigger Container Build
+      - name: "Trigger Engage Static Files Build"
         uses: peter-evans/repository-dispatch@v2
         with:
           token: ${{ secrets.CI_WEBHOOK_TOKEN }}
@@ -98,8 +108,8 @@ jobs:
             {
               "repo": {
                 "name": "${{ github.repository }}",
-                "branch": "${{ needs.build_cfg.outputs.REPO_BRANCH }}",
-                "tag": "${{ needs.build_cfg.outputs.REPO_TAG }}"
+                "ref_type": "${{ github.event.client_payload.repo.ref_type }}",
+                "ref_name": "${{ github.event.client_payload.repo.ref_name }}"
               },
               "image": {
                 "dockerfile": "${{ env.DOCKERFILE2USE }}",
@@ -107,21 +117,20 @@ jobs:
                 "name": "${{ needs.build_cfg.outputs.IMAGE_NAME }}",
                 "tag": "${{ needs.build_cfg.outputs.IMAGE_TAG }}",
                 "build_args": [
+                  "BRAND_NAME=engage",
+                  "FROM_STAGE=${{ env.FROM_LAYER }}",
                 ]
               },
               "callback": {
                 "repository": "${{ github.repository }}",
-                "event_type": "build_layer2",
-                "error_type": "build_layer1_error",
+                "event_type": "build_layer_engage",
+                "error_type": "build_layer_engage_files_error",
                 "payload": {
                   "repo": {
-                    "ref_type": "${{ github.ref_type }}",
-                    "ref_name": "${{ github.ref_name }}",
-                    "branch": "${{ needs.build_cfg.outputs.REPO_BRANCH }}",
-                    "tag": "${{ needs.build_cfg.outputs.REPO_TAG }}"
+                    "ref_type": "${{ github.event.client_payload.repo.ref_type }}",
+                    "ref_name": "${{ github.event.client_payload.repo.ref_name }}"
                   },
-                  "layer1tag": "${{ needs.build_cfg.outputs.IMAGE_TAG }}",
-                  "layer1": "${{ needs.build_cfg.outputs.IMAGE_NAME }}:${{ needs.build_cfg.outputs.IMAGE_TAG }}"
+                  "layer": "${{ needs.build_cfg.outputs.IMAGE_NAME }}:${{ needs.build_cfg.outputs.IMAGE_TAG }}"
                 }
               }
             }
@@ -136,16 +145,13 @@ jobs:
       - name: Trigger Next Stage
         uses: peter-evans/repository-dispatch@v2
         with:
-          event-type: build_layer2
+          event-type: build_layer_engage
           client-payload: |-
             {
               "repo": {
-                "ref_type": "${{ github.ref_type }}",
-                "ref_name": "${{ github.ref_name }}",
-                "branch": "${{ needs.build_cfg.outputs.REPO_BRANCH }}",
-                "tag": "${{ needs.build_cfg.outputs.REPO_TAG }}"
+                "ref_type": "${{ github.event.client_payload.repo.ref_type }}",
+                "ref_name": "${{ github.event.client_payload.repo.ref_name }}"
               },
-              "layer1tag": "${{ needs.build_cfg.outputs.IMAGE_TAG }}",
-              "layer1": "${{ needs.build_cfg.outputs.IMAGE_NAME }}:${{ needs.build_cfg.outputs.IMAGE_TAG }}"
+              "layer": "${{ needs.build_cfg.outputs.IMAGE_NAME }}:${{ needs.build_cfg.outputs.IMAGE_TAG }}"
             }
   #endjob trigger-next-stage
